export const MOVIE_RECEIVED = 'MOVIE_RECEIVED';
export const MOVIE_SEARCH_RESULT_RECEIVED = 'MOVIE_SEARCH_RESULT_RECEIVED';
export const SET_IS_SEARCH_FETCHING = 'SET_IS_SEARCH_FETCHING';
export const SET_SEARCH_VALUE_IN_STATE = 'SET_SEARCH_VALUE_IN_STATE';
