export const ADD_LIST = 'ADD_LIST';
export const ADD_MOVIE_TO_ACTIVE_LIST = 'ADD_MOVIE_TO_ACTIVE_LIST';
export const DELETE_LIST = 'DELETE_LIST';
export const MOVE_MOVIE_DOWN_IN_ACTIVE_LIST = 'MOVE_MOVIE_DOWN_IN_ACTIVE_LIST';
export const MOVE_MOVIE_UP_IN_ACTIVE_LIST = 'MOVE_MOVIE_UP_IN_ACTIVE_LIST';
export const REMOVE_MOVIE_FROM_ACTIVE_LIST = 'REMOVE_MOVIE_FROM_ACTIVE_LIST';
export const RENAME_LIST = 'RENAME_LIST';
export const SET_ACTIVE_LIST = 'SET_ACTIVE_LIST';
